services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_USER: root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/checkouter
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres-data:
